### ISSUE TITLE
Revisar y definir Landing Común

### ISSUE THREAD

**Issue by naranjitagolden** [jointDeveloper/Ejercicio#21]
Escoger dentro de los diseños propuestos en realtime board cual es el más sencillo de implementar y definir las microtareas para poder desarrollarlo exitosamente entre todas

**Comment by carogomezt** [comment]
Definir temas para que cada una revise y exponga a las demás

**Comment by naranjitagolden** [comment]
<img width="869" alt="screen shot 2016-03-08 at 9 38 27 pm" src="https://cloud.githubusercontent.com/assets/10857460/13623652/30a2cad8-e576-11e5-89f2-530318e0fd65.png">

**Comment by arendondiosa** [comment]
<img src="https://raw.githubusercontent.com/jointDeveloper/Aprendizaje-Web/gh-pages/Design/home.jpg">

Diseño: Por Maria Paz
