### ISSUE TITLE
TEMAS - y adelanto

### ISSUE THREAD

**Issue by naranjitagolden** [jointDeveloper/Ejercicio#24]
Cada una puede escoger un tema, y que en base o con base, adelante una parte del ejercicio común que le correspodería

**Comment by naranjitagolden** [comment]
Naranjita
Yen
Vanessa
Carolina J
Tatiana
Giseth
Carolina G 
Angie 

GRID
ROW - COLUMN 
VIDEO
IMAGEN 
RESPONSIVE 
float:left;
 position: relative; 

FOOTER Y LOGONAVBAR
13DIVS
4 COLUMNAS
3 FILAS
STYLOS, Colores y tipo de letra   CONTAINER

**Comment by YensyGomez** [comment]
footer y LogoNavBar  Yen Gómez

**Comment by YensyGomez** [comment]
div e Imagenes Carolina Jimenez Gómez

**Comment by Meyito** [comment]
CSS Position y Float :)

**Comment by carolinajimenez26** [comment]
- [ ] Menús Pegajosos (sticky) --> html, css, javascript

https://www.youtube.com/watch?v=F-AyzkhkSU8

**Comment by arendondiosa** [comment]
https://github.com/jointDeveloper/Aprendizaje-Web/wiki/Reuniones
