### ISSUE TITLE
Organización

### ISSUE THREAD

**Issue by carolinajimenez26** [jointDeveloper/Ejercicio#27]
- [x] Cambiar el nombre del repositorio por creación página web, o algo por el estilo.
- [x]  Cambiar el README del inicio por uno que cuente qué se está haciendo y el porqué.

**Comment by pin3da** [comment]
- [x] Agregar en el README.md una guía de contribución corta que explique a las nuevas personas la manera en que trabaja el grupo (creación de issues, branches, pull request, etc.)  <--- #49
