### ISSUE TITLE
Organizar home

### ISSUE THREAD

**Issue by carolinajimenez26** [jointDeveloper/Ejercicio#34]
- [x] Organizar los cuadritos, que ocupen el espacio que son, de acuerdo al diseño

<img src="https://raw.githubusercontent.com/jointDeveloper/Aprendizaje-Web/gh-pages/Design/home.jpg">

**Comment by arendondiosa** [comment]
@carolinajimenez26 explique bien el issue...a que se refiere con "espacio que son" XD

**Comment by carolinajimenez26** [comment]
abralo y verás... Ya son clickeables. @aerendon

**Comment by arendondiosa** [comment]
Ahhhh @carolinajimenez26 , entonces a lo que usted se refiere es redistribuir el espacio que se tiene de acuerdo al diseño de Maria Paz :v

**Comment by carolinajimenez26** [comment]
Esoooooooooooooo, no lo pudo haber dicho mejor.

**Comment by arendondiosa** [comment]
#38 Revisar tamaño máximo de pantalla y bordes negros
