### ISSUE TITLE
Revisar Contactenos

### ISSUE THREAD

**Issue by arendondiosa** [jointDeveloper/Ejercicio#39]
<img src="https://raw.githubusercontent.com/jointDeveloper/Aprendizaje-Web/fa821f25b70245791afdca5654a59cf403e5a275/Design/Contacto.png">

Por favor evaluar el mockup y sugerir cambios

---

Agradecimientos especiales a Alejo Moreno

**Comment by sebas095** [comment]
cool :sunglasses:
