### ISSUE TITLE
Eventos

### ISSUE THREAD

**Issue by carolinajimenez26** [jointDeveloper/Ejercicio#58]
- [x] Hay que organizar que las imágenes que son muy altas no se salgan del panelUp.
- [x] También hay que poner los diálogos a cada imágen.
- [x] Que se pueda pasar las imágenes con las flechas del teclado.
- [x] Que cuando se pase el mouse por cada imágen, se resalte, y que se vea grande arriba.
- [x] Que cuando se le de click a una imágen, se siga mostrando desde allí.
  - [x] Posicionar event-box para que quede centrado a la página

**Comment by carolinajimenez26** [comment]
Página guía de eventos

> https://templated.co/transit
> **https://www.airbnb.com/**

Otros templates:

> https://templated.co/

Página guía para galería de imágenes:

> http://tympanus.net/Tutorials/ResponsiveImageGallery/

General:

> http://www.zuperstores.com/wizard/business/index.html#panelBlock1

Charlas:

> http://mikekus.com/

Colores, estilos:

> http://www.ibm.com/design/

**Comment by arendondiosa** [comment]
#83 - Actualización

**Comment by carolinajimenez26** [comment]
- [x] Arreglar que en los eventos, cuando se pasa el mouse por el nombre del evento "Evento#", desaparece el efecto de contraste de la imágen.
- [x] Arreglar contenido del texto en el lightbox de codeparty para que no se salga la letra del contenedor, para que se autoajuste el tamaño de la fuente

**Comment by carolinajimenez26** [comment]
- [ ] Arreglar diseño del dropdown del nav
- [x] Arreglar links en la página de eventos
- [ ] Organizar sección de las charlas
- [ ] Organizar página codeparty para que sea responsive

**Comment by aerendon** [comment]
[Branch del issue](https://github.com/jointDeveloper/Aprendizaje-Web/tree/eventos)

PD: RWD - Responsive Web Desing comprende principalmente las filosofías Mobile First, Desktop First

**Comment by carolinajimenez26** [comment]
- [x] Agregar descripción en las imágenes de la CodeParty
- [ ] Modificar flechas para que queden como las del index
- [ ] Agregar botón para el scroll (imágen ppal)
