### ISSUE TITLE
URL relativas

### ISSUE THREAD

**Issue by pin3da** [jointDeveloper/Ejercicio#61]
Estaba viendo en el README que deben hacer un montón de cambios para probar local, esto dificulta mucho el proceso y es muy propenso a bugs.

Al utilizar URL relativas, por ejemplo `$.getJSON("./data.json", function (data) {..`  (con punto), se debería resolver este problema.

Open to discussion, y felicitaciones por ese buen trabajo que están haciendo :+1:

**Comment by arendondiosa** [comment]
@pin3da gracias :heart_eyes: . @sebas095 ya está corrigiendo eso

**Comment by sebas095** [comment]
Listo ya hicce los cambios me toco fue en el json de perfiles poner doble punto por lo que estaba una carpeta mas pero ya todo quedo, @pin3da gracias :+1:
